version: '3.3'

services:
  my-mongo:
    image: mongo:4.4.6
    environment:
      - MONGO_INITDB_DATABASE=nestjs_mongo
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=secreta123
    ports:
      - '27017:27017'
    volumes:
      - ./mongo_data:/data/db

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    user: '$UID:$GID'
    ports:
      - '5050:80'
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin

  mysqlcali:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=usuario1
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3307:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysqlcali
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '8080:80'
    volumes:
      - ./phpmyadmin_data:/var/lib/phpmyadmin
